server:
  port: 8010
spring:
  application:
    name: ms-consumer-hello-feign-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true