server:
  port: 8010
spring:
  application:
    name: microservice-consumer-hello-ribbon
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true