server:
  port: 8011
spring:
  application:
    name: ms-consumer-hello-ribbon-with-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    hostname: ribbon