package com.muarine.example.orm;

import java.util.Date;

public class ShakeUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.appid
     *
     * @mbggenerated
     */
    private String appid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.openid
     *
     * @mbggenerated
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.nick_name
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.head
     *
     * @mbggenerated
     */
    private String head;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.update_time
     *
     * @mbggenerated
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.state
     *
     * @mbggenerated
     */
    private Boolean state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.subscribe_time
     *
     * @mbggenerated
     */
    private Long subscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.unsubscribe_time
     *
     * @mbggenerated
     */
    private Long unsubscribeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.unionid
     *
     * @mbggenerated
     */
    private String unionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.sex
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.mobile
     *
     * @mbggenerated
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column shake_user.mobile_time
     *
     * @mbggenerated
     */
    private Date mobileTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.id
     *
     * @return the value of shake_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.id
     *
     * @param id the value for shake_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.appid
     *
     * @return the value of shake_user.appid
     *
     * @mbggenerated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.appid
     *
     * @param appid the value for shake_user.appid
     *
     * @mbggenerated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.openid
     *
     * @return the value of shake_user.openid
     *
     * @mbggenerated
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.openid
     *
     * @param openid the value for shake_user.openid
     *
     * @mbggenerated
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.nick_name
     *
     * @return the value of shake_user.nick_name
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.nick_name
     *
     * @param nickName the value for shake_user.nick_name
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.head
     *
     * @return the value of shake_user.head
     *
     * @mbggenerated
     */
    public String getHead() {
        return head;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.head
     *
     * @param head the value for shake_user.head
     *
     * @mbggenerated
     */
    public void setHead(String head) {
        this.head = head == null ? null : head.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.create_time
     *
     * @return the value of shake_user.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.create_time
     *
     * @param createTime the value for shake_user.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.update_time
     *
     * @return the value of shake_user.update_time
     *
     * @mbggenerated
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.update_time
     *
     * @param updateTime the value for shake_user.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.state
     *
     * @return the value of shake_user.state
     *
     * @mbggenerated
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.state
     *
     * @param state the value for shake_user.state
     *
     * @mbggenerated
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.subscribe_time
     *
     * @return the value of shake_user.subscribe_time
     *
     * @mbggenerated
     */
    public Long getSubscribeTime() {
        return subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.subscribe_time
     *
     * @param subscribeTime the value for shake_user.subscribe_time
     *
     * @mbggenerated
     */
    public void setSubscribeTime(Long subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.unsubscribe_time
     *
     * @return the value of shake_user.unsubscribe_time
     *
     * @mbggenerated
     */
    public Long getUnsubscribeTime() {
        return unsubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.unsubscribe_time
     *
     * @param unsubscribeTime the value for shake_user.unsubscribe_time
     *
     * @mbggenerated
     */
    public void setUnsubscribeTime(Long unsubscribeTime) {
        this.unsubscribeTime = unsubscribeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.unionid
     *
     * @return the value of shake_user.unionid
     *
     * @mbggenerated
     */
    public String getUnionid() {
        return unionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.unionid
     *
     * @param unionid the value for shake_user.unionid
     *
     * @mbggenerated
     */
    public void setUnionid(String unionid) {
        this.unionid = unionid == null ? null : unionid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.remark
     *
     * @return the value of shake_user.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.remark
     *
     * @param remark the value for shake_user.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.sex
     *
     * @return the value of shake_user.sex
     *
     * @mbggenerated
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.sex
     *
     * @param sex the value for shake_user.sex
     *
     * @mbggenerated
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.province
     *
     * @return the value of shake_user.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.province
     *
     * @param province the value for shake_user.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.city
     *
     * @return the value of shake_user.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.city
     *
     * @param city the value for shake_user.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.country
     *
     * @return the value of shake_user.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.country
     *
     * @param country the value for shake_user.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.mobile
     *
     * @return the value of shake_user.mobile
     *
     * @mbggenerated
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.mobile
     *
     * @param mobile the value for shake_user.mobile
     *
     * @mbggenerated
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column shake_user.mobile_time
     *
     * @return the value of shake_user.mobile_time
     *
     * @mbggenerated
     */
    public Date getMobileTime() {
        return mobileTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column shake_user.mobile_time
     *
     * @param mobileTime the value for shake_user.mobile_time
     *
     * @mbggenerated
     */
    public void setMobileTime(Date mobileTime) {
        this.mobileTime = mobileTime;
    }
}